package game;

/*
 * ImageFrame.java
 *
 * Created on May 27, 2009, 11:38 PM
 */


import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Panel;
import java.awt.image.RenderedImage;
import java.awt.geom.AffineTransform;

/**
 *
 * @author  parnell
 */

public class ImageFrame extends java.awt.Frame {
	private static final long serialVersionUID = 1L;
	private final static AffineTransform ident = new AffineTransform ();

	public class PaintPanel extends Panel {
        	private static final long serialVersionUID = 1L;
		RenderedImage bi;
		public void paint(Graphics g) {
			Graphics2D g2 = (Graphics2D) g;
			g2.drawRenderedImage(bi,ident);
                        
                }
                
		public void setImage(RenderedImage bi){
			this.bi = bi;
			repaint();
		}

	}

    /** Creates new form ImageFrame */
    public ImageFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        more_time = new java.awt.Button();
        tf_secs = new java.awt.TextField();
        label1 = new java.awt.Label();
        panel3 = new java.awt.Panel();
        panel5 = new java.awt.Panel();
        lb_history = new java.awt.Label();
        bt_backward_history = new java.awt.Button();
        bt_forward_history = new java.awt.Button();
        tf_history_number = new java.awt.TextField();
        panel6 = new java.awt.Panel();
        tf_mvtohistory = new java.awt.TextField();
        lb_micro_history = new java.awt.Label();
        bt_mv_history_backward = new java.awt.Button();
        bt_mv_history_forward = new java.awt.Button();
        tf_mv_history = new java.awt.TextField();
        bt_mv_previous = new java.awt.Button();
        bt_mv_next = new java.awt.Button();
        tf_mv = new java.awt.TextField();
        panel4 = new java.awt.Panel();
        cb_show_board = new java.awt.Checkbox();
        cb_show_move = new java.awt.Checkbox();
        bt_make_guess = new java.awt.Button();
        panel7 = new java.awt.Panel();
        ip_1 = new PaintPanel();
        ip_2 = new PaintPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panel1.setLayout(new java.awt.GridLayout(3, 1));

        more_time.setActionCommand("more_time");
        more_time.setLabel("Start");
        panel2.add(more_time);

        tf_secs.setText("63");
        tf_secs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_secsActionPerformed(evt);
            }
        });
        panel2.add(tf_secs);

        label1.setText("secs");
        panel2.add(label1);

        panel1.add(panel2);

        panel3.setLayout(new java.awt.GridLayout(1, 0));

        lb_history.setText("Board");
        panel5.add(lb_history);

        bt_backward_history.setLabel("<");
        bt_backward_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backward_historyActionPerformed(evt);
            }
        });
        panel5.add(bt_backward_history);

        bt_forward_history.setLabel(">");
        panel5.add(bt_forward_history);

        tf_history_number.setText("0338448");
        panel5.add(tf_history_number);

        panel3.add(panel5);

        tf_mvtohistory.setEditable(false);
        tf_mvtohistory.setEnabled(false);
        tf_mvtohistory.setText("333");
        panel6.add(tf_mvtohistory);

        lb_micro_history.setText("Move");
        panel6.add(lb_micro_history);

        bt_mv_history_backward.setLabel("<");
        panel6.add(bt_mv_history_backward);

        bt_mv_history_forward.setLabel(">");
        panel6.add(bt_mv_history_forward);

        tf_mv_history.setText("0338");
        panel6.add(tf_mv_history);

        bt_mv_previous.setLabel("<");
        panel6.add(bt_mv_previous);

        bt_mv_next.setLabel(">");
        panel6.add(bt_mv_next);

        tf_mv.setText("0338");
        panel6.add(tf_mv);

        panel3.add(panel6);

        panel1.add(panel3);

        cb_show_board.setLabel("Show Board");
        cb_show_board.setState(true);
        panel4.add(cb_show_board);

        cb_show_move.setLabel("Show Move");
        cb_show_move.setState(true);
        panel4.add(cb_show_move);

        bt_make_guess.setLabel("Make Guess File");
        panel4.add(bt_make_guess);

        panel1.add(panel4);

        add(panel1, java.awt.BorderLayout.NORTH);

        panel7.setLayout(new java.awt.GridLayout(1, 0));
        panel7.add(ip_1);
        panel7.add(ip_2);

        add(panel7, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

private void tf_secsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_secsActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tf_secsActionPerformed

private void bt_backward_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backward_historyActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_bt_backward_historyActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button bt_backward_history;
    public java.awt.Button bt_forward_history;
    public java.awt.Button bt_make_guess;
    public java.awt.Button bt_mv_history_backward;
    public java.awt.Button bt_mv_history_forward;
    public java.awt.Button bt_mv_next;
    public java.awt.Button bt_mv_previous;
    public java.awt.Checkbox cb_show_board;
    public java.awt.Checkbox cb_show_move;
    public PaintPanel ip_1;
    public PaintPanel ip_2;
    private java.awt.Label label1;
    public java.awt.Label lb_history;
    private java.awt.Label lb_micro_history;
    public java.awt.Button more_time;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private java.awt.Panel panel7;
    public java.awt.TextField tf_history_number;
    public java.awt.TextField tf_mv;
    public java.awt.TextField tf_mv_history;
    public java.awt.TextField tf_mvtohistory;
    public java.awt.TextField tf_secs;
    // End of variables declaration//GEN-END:variables

}
